name: Mi primer workflow

on:
  push:
  workflow_dispatch:

jobs:
  primero:
    runs-on: ubuntu-latest

    steps:
      - name: Primer job
        run: echo "Este es el primer job"

  segundo:
    needs: primero #significa que para poder ejecutar este segundo job, es necesario que primero se ejecute el primero, depende el primero para poder ejecutarse
    runs-on: ubuntu-latest

    steps:
      - name: Segundo job
        run: echo "Este es el segundo job"
