name: Mi primer workflow

on:
  push:
  workflow_dispatch:

jobs:
  primero:
    runs-on: ubuntu-latest

    steps:
      - name: Primer job
        run: echo "Este es el primer job"

  segundo:
    runs-on: ubuntu-latest

    steps:
      - name: Segundo job
        run: echo "Este es el segundo job"
